### ISSUE TITLE
Tests randomly fail in Github CI, why?

### ISSUE THREAD

**Issue by cinnamon-bun** [earthstar-project/earthstar#82]
In Github CI, the tests keep randomly failing, usually only for node 12.x.  Here's [an example failed run](https://github.com/earthstar-project/earthstar/actions/runs/625839038).

The failure is always this:
```
  FAIL  build/test/crypto.test.js 62 OK 106.576ms
  command: /opt/hostedtoolcache/node/12.21.0/x64/bin/node
  args:
    - -r
    - /home/runner/work/earthstar/earthstar/node_modules/esm/esm.js
    - build/test/crypto.test.js
  exitCode: null
  signal: SIGSEGV
```

I've never seen this happen on my own computer running MacOS.

`crypto.test.ts` is exercising this code:
* https://github.com/earthstar-project/earthstar/blob/main/src/crypto/crypto.ts
    * https://github.com/earthstar-project/earthstar/blob/main/src/crypto/cryptoChloride.ts
        * [chloride](https://www.npmjs.com/package/chloride) aka sodium for keypair creation, signing, signature verification
        * native node `crypto` for sha256
* https://github.com/earthstar-project/earthstar/blob/main/src/crypto/encoding.ts
    * [multibase](https://www.npmjs.com/package/multibase) base32 encoding and decoding

Random guesses why this might be happening:
* Something about node 12's sha256, maybe try using the one from `chloride` instead?
* Github timeout on long tests?  But the crypto tests are not long
* Running out of memory?
* We're running tests with `-Rspecy` to show code coverage.  Is that making tests run slower or use more memory?  Maybe try disabling code coverage by default for `npm test`?
* Multibase maybe segfaults under rare conditions?
